### ISSUE TITLE
Is it possible to set a station to a known "frequency"?

### ISSUE THREAD

**Issue by chunkysteveo** [raphaelyancey/Virtual_FM_Band#3]
Great project, it's inspired me to make a GTA VC version, using a real 1980's radio/cassette as the main "guts"! Can't wait to get it started. But i'd like to expand on what you have achieved so far.

One of the things that would be really great would be to "tune" the radio to a known frequency of the station, e.g. Wave is Wave103, Emotion is 98.3. So using the existing tuning dial (which are usually POTS) or connecting it physically to a rotatory encoded so the "tuning" is done with the rotary and the POT just moves the little Freq marker. We could "tune" to the station frequency, and the software know what station it is on. I think there are enough tutorials out there to either read a POT value or read and keep track of the ROTARY so you know "where it is" on the tuning dial - but could you set a config so you could list the tracks and state they are at location X, Y or Z on the virtual frequency range, rather than just evenly spaced out?

I waffle on - but that was my thought! Do you have any ideas or suggestions for this? Also any update on adding in the static noise? I understand I can add it as "tracks" in between the channels which would work well, but like you have said, you would need a static track per gap.

Future expansion for me would be to add in a "mix tape" ala 'Guardians of the Galaxy' style and maybe have this as a NFC chip on the tape (the tape deck is busted!) so physically load it in, Raspberry Pi detects and reads the chip and plays a custom MP3 stream. Another idea!

Cheers anyhow for a cool project!

Steve

**Comment by raphaelyancey** [comment]
Thanks Steve! Good ideas.

To put files on a specific virtual frequency shouldn't be hard. Assignations are done [here](https://github.com/raphaelyancey/Virtual_FM_Band/blob/master/src/main.py#L72) and I can imagine two quick'n'dirty hacks:

- In the .env file, declaring stringified tuples

```bash
# .env
ASSIGNED_VFREQS="[[filepath, vfreq], ...]"
```
```python
# main.py
assigned_vfreqs = json.loads(os.getenv('ASSIGNED_VFREQS'))  # -> Native Python array with the tuples
```
... and then assign frequencies based on those informations.

That lead me to think it might be good to switch to a Yaml config file, handling lists/arrays.

- Imposing a filename nomenclature and specifying informations in the filename itself like `([ORDERING_CHARS]__)[STATION_NAME]__[VFREQ].ext`. I find it better suited since all informations are *in* the file(name) itself, at least before moving to a more structured file and metadata management.

Loading all the files the way it's done now has the advantage of being plug'n'play.

Another thing that comes in mind is the calibration. The software must know how many encoder ticks there are between your radio/cassette 87.5Mhz and 108Mhz positions to be able to sync.

On the noise thing, no updates. To be honest I didn't digged into the project since the blog posts, but I eventually will in a few weeks.

If you know your way with Python I'd gladly consider your pull requests!

**Comment by chunkysteveo** [comment]
Thanks for the update Raphael, I wasn't even sure if you were actively looking at this or not, so thanks for at least getting back to me! It all sounds very cool and thanks for the pointers. I am not much of a Python man, but they may be something to help get my head stuck into?!

If and when I get my physical part complete, I will let you know!

Cheers,

Steve
